version: "3.9"

services:
  tryton-postgres:
    image: postgres:16
    container_name: tryton-postgres
    environment:
      POSTGRES_USER: rtryton
      POSTGRES_PASSWORD: "7731"
      POSTGRES_DB: postgres
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  tryton:
    image: tryton/tryton:7.6
    container_name: tryton
    depends_on:
      - tryton-postgres
    environment:
      TRYTOND_DATABASE_URI: "postgresql://rtryton:7731@tryton-postgres:5432/"
      TRYTOND_DATABASE_LIST: "*"
    ports:
      - "8100:8000"
    volumes:
      - tryton_filestore:/var/lib/trytond
      - ./modules:/modules

volumes:
  pgdata:
  tryton_filestore:
