version: "3.9"

services:
  tryton-postgres:
    image: postgres:16
    container_name: tryton-postgres
    environment:
      POSTGRES_USER: rtryton
      POSTGRES_PASSWORD: "7731"
      POSTGRES_DB: postgres
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  tryton:
    image: tryton/tryton:7.6
    container_name: tryton
    depends_on:
      - tryton-postgres
    environment:
      TRYTOND_DATABASE_URI: "postgresql://rtryton:7731@tryton-postgres:5432/"
      TRYTOND_DATABASE_LIST: "*"
    ports:
      - "8100:8000"
    volumes:
      - tryton_filestore:/var/lib/trytond
      # სწორი გადამისამართებები თქვენი მოდულებისთვის:
      - ./modules/account_ge:/usr/local/lib/python3.11/dist-packages/trytond/modules/account_ge
      - ./modules/currency_ge:/usr/local/lib/python3.11/dist-packages/trytond/modules/currency_ge
      - ./modules/ge_calendar:/usr/local/lib/python3.11/dist-packages/trytond/modules/ge_calendar
      - ./modules/hr_payroll:/usr/local/lib/python3.11/dist-packages/trytond/modules/hr_payroll
      - ./modules/income_rs:/usr/local/lib/python3.11/dist-packages/trytond/modules/income_rs
      - ./modules/party_ge_identifier:/usr/local/lib/python3.11/dist-packages/trytond/modules/party_ge_identifier

volumes:
  pgdata:
  tryton_filestore: